### ISSUE TITLE
Allow one space

### ISSUE THREAD

**Issue by cedvan** [WyriHaximus/HtmlCompress#23] opened 2016-09-07 08:41 UTC
Hi,

it would be must to be able :

``` html
<ul> <ul>     =>     </ul> </ul>   # Keep because one space
```

``` html
<ul>  <ul>    =>     </ul></ul>   # Compress because more one space
```

Thank you for job ;)

**Comment by WyriHaximus** [comment] 2017-12-26 20:28
Hey sorry for the late reply, been busy with https://github.com/reactphp/http/releases/tag/v0.8.0 the past few months. I'll be adding an edge case test for this later today/tomorrow ensuring this works as intended. Thank you for reporting, I'll keep you posted :+1:

**Comment by WyriHaximus** [comment] 2019-07-07 22:55
This has been resolved for some time now so closing this issue

**Closed by WyriHaximus** 2019-07-07 22:55 UTC
